qwen2.5_7b: {YOUR_PATH_TO_MODEL}
qwen2.5_14b: {YOUR_PATH_TO_MODEL}
qwen2.5_32b: {YOUR_PATH_TO_MODEL}
qwen2.5_32b_fp8: {YOUR_PATH_TO_MODEL}
qwen2.5_72b: {YOUR_PATH_TO_MODEL}
llama3.3_70b: {YOUR_PATH_TO_MODEL}
baichuan_14b: {YOUR_PATH_TO_MODEL}
baichuan_m2_32b: {YOUR_PATH_TO_MODEL}
qwq_preview: {YOUR_PATH_TO_MODEL}
qwen3_1.7b: {YOUR_PATH_TO_MODEL}
qwen3_8b: {YOUR_PATH_TO_MODEL}
qwen3_32b: {YOUR_PATH_TO_MODEL}
qwen3_235b: {YOUR_PATH_TO_MODEL}
medgemma_4b: {YOUR_PATH_TO_MODEL}
medgemma_27b: {YOUR_PATH_TO_MODEL}
openbiollm_70b: {YOUR_PATH_TO_MODEL}
palmyra_med_70b: {YOUR_PATH_TO_MODEL}
gpt_oss_20b: {YOUR_PATH_TO_MODEL}
gpt_oss_120b: {YOUR_PATH_TO_MODEL}
